application: map-of-life
version: islands
runtime: python27
threadsafe: true
api_version: 1

inbound_services:
- warmup

builtins:
- remote_api: on

handlers:

- url: /js
  static_dir: js
  
- url: /css
  static_dir: css

- url: /
  script: app.application

- url: /.*
  script: app.application


